In [ ]:
print("hello")

hello


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


ctrl+ enter : 셀실행

shift + enter : 셀 실행 후다음

In [ ]:
import tensorflow as tf
print(tf.__version__) #버전 확인

2.17.0


# **초기화 관련 편의 함수**

In [12]:
Y = np.zeros((3,3))
Y = np.ones((3,3),dtype='int32')
Z=np.empty((3,3))

# Numpy 실습

In [11]:
import numpy as np
x = np.array([0.1,0.2,0.3])
print(x)
print(x.shape)
print(x.dtype)
y=np.array(((1,2,3),(4,5,6)))
print(y)
print(y.dtype)
print(y.shape)


[0.1 0.2 0.3]
(3,)
float64
[[1 2 3]
 [4 5 6]]
int64
(2, 3)


In [13]:
import numpy as np

A = np.array([])
for i in range(3):
    A = np.append(A,[1,2,3])
print(A)

[1. 2. 3. 1. 2. 3. 1. 2. 3.]


# 단순한 시퀀스는
`range()`함수의 실수버전인 `arrange(from,to,step)` 이나

`linspace(from,to,npoints)`를 사용하면 편리

또한 단위행렬을 위한 `eye(n)`함수를 제공한다.

In [16]:
print(np.arange(1,2,0.1))

print(np.arange(10))

print(np.arange(10.))

print(np.linspace(0.,20.,11))

print(np.eye(3))

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
